#Robot
print ("Plese enter a character for the eye")
eye = input("")
print ("Beep's expresstion is as fallows")
print("##########")
print("#" ,eye ,eye,"\t #")
print("#        #")
print("# ------ #")
print("##########")
print("\t##\n\t##")
print("####\t#######")
print("#      #")
print("#      #")
print("#      #")
print("########")
print("#      #\n#      #\n")